name = "Math Battle v1.0"

[store]
id="com.github.M4ss1ck.mathBattle"
version_name=1.0
version_code=1
author="M4ss1ck"
author_email="massick@systemli.org"
description="Show your math skills! How high can you score?"